@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Triptop - Component Diagram (Boekingsverzoeken)

Container(trip_trop, "TripTop", "React, Spring Boot", "Hoofdapplicatie")
Container(db, "Database", "SSMS", "Opslag van gegevens")
System_Ext(booking_com_api, "Booking.com API", "Geeft informatie over accommodaties, vluchten, en autohuur, en maakt boekingen.")

Container_Boundary(backend, "API Calls System") {
    Component(reservatie_controller, "Reservatie Controller", "Spring Boot", "Verstuurt boeking aanvragen")
    Component(volgorde_checker, "Volgorde Checker", "Spring Boot", "Handelt meerdere aanroepen correct af")
    Component(booking_adapter, "Booking Adapter", "Spring Boot", "Connecteert met Booking.com en zorgt voor correcte informatie afhandeling")
    Component(trip_repository, "Trip Repository", "Spring Boot", "Slaat alle data op in de database")
}

Rel(trip_trop, reservatie_controller, "1. Maakt boeking aan via", "REST")
Rel(reservatie_controller, booking_adapter, "2. Verstuurt boekingsverzoek naar", "REST")
Rel(booking_adapter, booking_com_api, "3. Haalt boeking informatie op van", "JSON / HTTPS")
Rel(booking_adapter, volgorde_checker, "4. Verstuurt gegevens voor verwerking naar", "REST")
Rel(volgorde_checker, trip_repository, "5. Slaat de definitieve boekingsinformatie op in", "REST")
Rel(trip_repository, db, "6. Slaat gegevens op in", "JDBC")
Rel(trip_repository, booking_adapter, "7. Stuurt opgeslagen gegevens terug naar", "REST")
Rel(booking_adapter, reservatie_controller, "8. Stuurt bevestigde gegevens naar", "REST")
Rel(reservatie_controller, trip_trop, "9. Stuurt bevestiging naar gebruiker", "JSON / HTTPS")


@enduml
