@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


title Container diagram voor Triptop Applicatie

Person(reiziger, Reiziger, "Een reiziger die een reis wil samenstellen.")
Person(reis_agent, Reisagent, "Medewerker van een reisbureau die de reiziger helpt met vragen en problemen.")

System_Boundary(c1, "Triptop omgeving") {
    Container(frontend, "Frontend Applicatie", "React.js, Vite", "De website waar de reiziger zijn reis kan samenstellen en hulp kan vragen aan de reisagenten wanneer nodig.")
    Container(backend, "Backend", "Java, Spring Boot", "De achterkant van de applicatie, waar alle logica wordt beheerd en verstuurd door de voorkant en opslag van het systeem.")
    ContainerDb(database, "Database", "DBMS", "De opslagplaats voor alle informatie over de gebruikers en reisinformatie.")
    Container(api_gateway, "API Gateway", "Javascript", "De poort tussen de triptop omgeving en informatie die wordt verkregen van buitenaf.")
}

System_Ext(overnachting_vervoer, "Booking COM API", "Geeft informatie over accommodaties, autohuur, vluchten en attracties, de beschikbaarheid hiervan en boekt tickets.")
System_Ext(eten, "Uber Eats API", "Toont restaurants en maakt reserveringen.")
System_Ext(identiteit, "WireMock API", "Authenticatieservice die reizigers hun identiteit verifieert door SSO (single sign-on).")
System_Ext(maps, "Maps Data API", "Geeft kaart weer en plant routes.")

Rel(reiziger, frontend, "Kan reis samenstellen, boeken, aanpassen, annuleren en betalen via", "HTTPS")
Rel(reis_agent, frontend, "Is bereikbaar voor vragen en problemen via", "HTTPS")

Rel(frontend, backend, "Krijgt reisinformatie via", "JSON / HTTPS")
Rel(backend, database, "Stuurt en ontvang relevante data via", "SQL")
Rel(backend, api_gateway, "Roept externe providers aan via", "JSON / HTTPS")

Rel(api_gateway, overnachting_vervoer, "Controleert beschikbaarheid en boekt via", "HTTPS / JSON")
Rel(api_gateway, eten, "Bestelt maaltijden en boekt reserveringen via", "HTTPS / JSON")
Rel(api_gateway, identiteit, "Verifieert gebruikersidentiteit via", "HTTPS / JSON")
Rel(api_gateway, maps, "Haalt route-informatie op via", "HTTPS / JSON")


@enduml
