@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Triptop - Dynamic Diagram (Boekingsverzoeken)

Container(trip_trop, "TripTop", "React, Spring Boot", "Hoofdapplicatie")
Container(db, "Database", "NoSQL", "Opslag van gegevens")
System_Ext(booking_api, "Booking.com API", "Geeft informatie over accommodaties, vluchten, en autohuur, en maakt boekingen.")

Container_Boundary(backend, "API Calls System") {
    Component(reservatie_controller, "Reservatie Controller", "Spring Boot", "Verstuurt boeking aanvragen")
    Component(booking_service, "Booking Service", "Spring Boot", "Verwerkt aanvragen en schakelt states")
    Component(booking_states, "Booking States", "Spring Boot", "Verschillende states die op volgorde worden afgehandeld")
    Component(booking_adapter, "Booking Adapter", "Spring Boot", "Connecteert met Booking.com en zorgt voor correcte informatie afhandeling")
    Component(trip_repository, "Trip Repository", "Spring Boot", "Slaat alle data op in de database")
}

Rel(trip_trop, reservatie_controller, "1. Maakt boeking aan via", "JSON / HTTPS")
Rel(reservatie_controller, booking_service, "2. Verstuurt boekingsverzoek naar", "REST")
Rel(booking_service, booking_states, "3. Stuurt boekingsverzoek naar", "REST")
Rel(booking_states, booking_adapter, "4. Vraagt gegevens op via", "JSON / HTTPS")
Rel(booking_adapter, booking_api, "5. Vraagt beschikbaarheid en prijzen op bij", "REST")
Rel(booking_adapter, booking_states, "6. Stuurt gekregen gegevens terug naar", "REST")
Rel(booking_states, booking_service, "7. Stuurt definitieve boekings gegevens naar", "REST")
Rel(booking_service, trip_repository, "8. Geeft gegevens door naar", "JSON")
Rel(trip_repository, db, "9. Slaat gegevens op in", "REST")
Rel(booking_service, reservatie_controller, "10. Stuurt bevestigde boekingsgegevens naar", "REST")
Rel(reservatie_controller, trip_trop, "11. Stuurt bevestiging naar gebruiker", "JSON / HTTPS")

@enduml
