@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title C4 Container diagram voor Triptop

Person(reiziger, "Reiziger", "Een reiziger die een reis wil samenstellen.")
Person(reisagent, "Reisagent", "Medewerker van een reisbureau die de reiziger helpt met vragen en problemen.")

System_Boundary(triptop_systeem, "Triptop") {
    Container(webapp, "Web Applicatie", "React", "Biedt de gebruikersinterface voor reizigers en reisagenten.")
    ContainerDb(database, "Database", "SQL", "Slaat alle reisgegevens, gebruikersinformatie, en boekingen op.")
    Container(api_gateway, "API Gateway", "", "Biedt een enkele toegangspunt voor alle API-aanvragen.")
    Container(backend, "Backend", "Spring Boot", "Behandelt de bedrijfslogica en gegevensverwerking.")
}

System_Ext(overnacht_system, "Overnachtingsprovider (Booking.com, AirBNB)", "Geeft informatie over accommodaties, de beschikbaarheid en reserveringen.")
System_Ext(vervoer_systeem, "Vervoersprovider (NS, KLM)", "Toont reisinformatie, de beschikbaarheid hiervan en boekt tickets.")
System_Ext(autohuur_systeem, "Autohuurprovider (Hertz, Sixt)", "Toont huurauto's, de beschikbaarheid hiervan en boekt deze.")
System_Ext(activiteit_systeem, "Excursies / Activiteiten provider (Tripadvisor, GetYourGuide)", "Toont excursies en activiteiten, hun beschikbaarheid en maakt reserveringen.")
System_Ext(eten_en_drinken_systeem, "Eten en drinken provider (Takeaway, Eet.nu)", "Toont restaurants en maakt reserveringen.")
System_Ext(identeits_systeem, "Identiteitsprovider", "Authenticatieservice die reizigers hun identiteit verifieert door SSO (single sign-on).")
System_Ext(maps_systeem, "Google Maps API", "Geeft kaart weer en plant routes.")

Rel(reiziger, webapp, "Kan reis samenstellen, boeken, aanpassen, annuleren en betalen via")
Rel(reisagent, webapp, "Is bereikbaar voor vragen en problemen via")
Rel(webapp, backend, "Maakt gebruik van", "REST API")
Rel(backend, api_gateway, "Maakt gebruik van", "REST API")
Rel_Back_Neighbor(database, backend, "Leest van en schrijft naar", "JDBC")
Rel(api_gateway, overnacht_system, "Controleert beschikbaarheid en boekt overnachting via", "REST API")
Rel(api_gateway, vervoer_systeem, "Controleert beschikbaarheid en boekt tickets via", "REST API")
Rel(api_gateway, autohuur_systeem, "Controleert beschikbaarheid en boekt autoreserveringen via", "REST API")
Rel(api_gateway, activiteit_systeem, "Controleert beschikbaarheid en boekt excursies en activiteiten via", "REST API")
Rel(api_gateway, eten_en_drinken_systeem, "Boekt maaltijden en reserveringen via", "REST API")
Rel(api_gateway, identeits_systeem, "Verifieert gebruikersidentiteit via", "WireMock")
Rel(api_gateway, maps_systeem, "Toont routeinformatie via", "REST API")

@enduml